/** nodeTypes with docs/help/zh/nodes/<type>.md (M-6 Wave 22, 45 total). */
export const HELP_DOC_NODE_TYPES = [
  'manualTrigger',
  'webhookTrigger',
  'scheduleTrigger',
  'errorTrigger',
  'subworkflowTrigger',
  'if',
  'switch',
  'merge',
  'loop',
  'humanApproval',
  'splitInBatches',
  'set',
  'json',
  'httpRequest',
  'wait',
  'code',
  'executeCommand',
  'executeWorkflow',
  'readWriteFile',
  'postgres',
  'llm',
  'llmStream',
  'ragRetrieve',
  'ragAnswer',
  'mcpClient',
  'workflow_run',
  'crewSequential',
  'crewHierarchical',
  'crewSupervisor',
  'groupChat',
  'aiAgent',
  'aiChatModel',
  'aiMemory',
  'aiKnowledge',
  'aiOutputParser',
  'toolMcp',
  'toolHttp',
  'toolWorkflow',
  'toolSkill',
  'toolSubagent',
  'toolRead',
  'toolWrite',
  'toolGrep',
  'toolShell',
  'toolWebSearch',
] as const;

export type HelpDocNodeType = (typeof HELP_DOC_NODE_TYPES)[number];
